---
title: "Zi-Frühindikatoren zu COVID-19"
output: 
  flexdashboard::flex_dashboard:
    navbar:
       - { title: "Dashboard", href: "Start_old.html", align: left }
       - { title: "Bundesländer", href: "Bundeslaender.html", align: left }
       - { title: "Kreise", href: "Kreise.html", align: left }
       - { title: "Impfungen", href: "Impfungen.html", align: left }
       - { title: "Projektion", href: "Projektion.html", align: left }
       - { title: "KBV-Report", href: "Report.html", align: left }
       - { title: "Impressum/Datenschutz", href: "Impressum.html", align: left }
    orientation: rows
    vertical_layout: scroll 
    logo: static/logo.png
    theme: bootstrap
    css: static/styles.css
    
---

Row
------------------------------------------------------------------------

### **Zi-Projektionen bis Zielinzidenzen erreicht werden** 

Wie lange dauert es, bis das Infektionsgeschehen auf ein bestimmtes Zielniveau abgesunken ist, ausgehend von der aktuellen Pandemiesituation? Wir verwenden die aktuelle Sieben-Tage-Inzidenz sowie den aktuellen R-Wert, um für eine gegebene Ziel-Sieben-Tage-Inzidenz das Datum zu berechnen, an dem diese Zielinzidenz erreicht wird. Als Zielinzidenzen verwenden wir dabei Werte aus dem Bereich des derzeit politisch Diskutierten (35, 50, 100 und 165). Für einen aktuellen R-Wert von größer oder gleich 1 kann eine niedrigere Zielinzidenz nicht erreicht werden. Zusätzlich berechnen wir auch das Datum, bei dem mit einem R-Wert von 0,7 die Zielinzidenz erreicht wird. Wir nehmen dabei an, dass bei gleichzeitiger Umsetzung von verschiedenen Maßnahmen zur Pandemiebegrenzung ein R=0,7 erreicht werden kann.\
Zur Berechnung des Zeitpunkts, an dem die Zielinzidenz erreicht wird, verwenden wir eine Formel der Zinseszinsrechnung: t=d*log(Nt/N0)/log(R). Der R-Wert (kleiner 1) entspricht “negativen Zinsen” für die Generationszeit d=5 Tage (die mittlere Zeit, bis eine neuinfizierte Person eine weitere Person ansteckt). Ausgehend vom “Startkapital”, der aktuellen Inzidenz N0, können wir dann die Zeit t bzw. den Zeitpunkt bis zum Erreichen des “Wunschkapitals”, also der Zielinzidenz Nt, bestimmen. In den untenstehenden Tabellen geben wir das Datum der verschiedenen Inzidenzprojektionen auf Bundesebene sowie für Bundesländer und Landkreise/kreisfreie Städte in Deutschland an.\
Insbesondere auf Kreisebene kann der R-Wert größere Sprünge je nach Infektionsgeschehen machen. **Liegt der R-Wert nur knapp unter 1, ergeben sich sehr lange Zeiträume, bis die Inzidenz deutlich sinkt. Die Inzidenzprojektion verwendet nur den aktuellen R-Wert und die aktuelle Sieben-Tage-Inzidenz, sie stellt keine exakte Prognose für die zukünftige Entwicklung dar. Diese hängt auch von anderen Faktoren ab.**

Row
-----------------------------------------------------------------------

### **Inzidenzprojektionen Bundesländer**

<div style = "width:99% !important; height:auto; margin: auto;">
```{r tableBL_projektionen}
DT::datatable(bl_projektionen,
              extensions = 'Responsive',
              options = list(paging = FALSE,
                             scrollY=1000,
                             scrollCollapse=TRUE,
                             pageLength=20,
                             columnDefs = list(list(className = 'dt-center', targets = 3:11),
                                               list(orderData = 12, targets = 4),
                                               list(visible = FALSE, targets = 12),
                                               list(orderData = 13, targets = 8),
                                               list(visible = FALSE, targets = 13),
                                               list(orderData = 14, targets = 5),
                                               list(visible = FALSE, targets = 14),
                                               list(orderData = 15, targets = 9),
                                               list(visible = FALSE, targets = 15),
                                               list(orderData = 16, targets = 6),
                                               list(visible = FALSE, targets = 16),
                                               list(orderData = 17, targets = 10),
                                               list(visible = FALSE, targets = 17),
                                               list(orderData = 18, targets = 7),
                                               list(visible = FALSE, targets = 18),
                                               list(orderData = 19, targets = 11),
                                               list(visible = FALSE, targets = 19)
                                               ),
                             searching = FALSE,
                             language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/German.json'),
                             server = FALSE,
                             initComplete = DT::JS("function(settings, json) {","$(this.api().table().header()).css({'background-color':'#0086C5','color': '#fff'});","}"))) %>% formatStyle(
  'Bundesland',
  target = 'row',
  fontWeight = styleEqual(c("Gesamt"), c('bold'))) %>%
  formatStyle(columns = c("Inzidenz<100 bei R(t) aktuell"), fontWeight = 'bold')

```
</div>

Row
-----------------------------------------------------------------------

### **Inzidenzprojektionen Kreise**

<div style = "width:99% !important; height:auto; margin: auto;">
```{r tableKreise_projektionen}
DT::datatable(kreise_projektionen %>% select(-`AGS (num)`, -Vorwarnzeit_ROR),
              extensions = 'Responsive',
              options = list(paging = TRUE,
                             scrollY=1000,
                             scrollCollapse=TRUE,
                             columnDefs = list(list(className = 'dt-center', targets = c(3, 5:12)),
                                               list(orderData = 13, targets = 5),
                                               list(visible = FALSE, targets = 13),
                                               list(orderData = 14, targets = 9),
                                               list(visible = FALSE, targets = 14),
                                               list(orderData = 15, targets = 6),
                                               list(visible = FALSE, targets = 15),
                                               list(orderData = 16, targets = 10),
                                               list(visible = FALSE, targets = 16),
                                               list(orderData = 17, targets = 7),
                                               list(visible = FALSE, targets = 17),
                                               list(orderData = 18, targets = 11),
                                               list(visible = FALSE, targets = 18),
                                               list(orderData = 19, targets = 8),
                                               list(visible = FALSE, targets = 19),
                                               list(orderData = 20, targets = 12),
                                               list(visible = FALSE, targets = 20)
                                               ),
                             searching = TRUE,
                             language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/German.json'),
                             server = FALSE,
                             initComplete = JS("function(settings, json) {","$(this.api().table().header()).css({'background-color':'#0086C5','color': '#fff'});","}"))) %>%
  formatStyle(columns = c("Inzidenz<100 bei R(t) aktuell"), fontWeight = 'bold')

```
</div>

Row
------------------------------------------------------------------------

### **Datenbasis- und Quellenangaben**

Für das Zi-Dashboard führen wir Zahlen aus unterschiedlichen Quellen zusammen und erweitern sie mit eigenen Berechnungen. Eine Übersicht über die benutzten Quellen finden Sie [hier](Daten.html).