##### Packages
library(DT)
library(DBI)
library(forcats)
library(EpiEstim)
library(plotly)
library(zicolors)
library(deSolve)
library(jsonlite)
library(readxl)
library(data.table)
library(dplyr)
library(glue)
library(lubridate)
library(tidyverse)
library(tidyr)
library(stringr)
library(ggplot2)
library(dtplyr)

ktf <- read_json("data/tabledata/kreise_table_faktenblatt.json", simplifyVector = TRUE)

plot(log1p(ktf$`7-Tage-Inzidenz`[ktf$Datum=="2020-12-06"]), log1p(ktf$`7-Tage-Inzidenz 80+`[ktf$Datum=="2020-12-06"]), xlim=c(0, 7.5), ylim=c(0,7.5), xlab = "STIgesamt", ylab="STI80+")
lines(c(0,7.5), c(0,7.5))